---
# Downloads and prepares the openwrt sources by applying patches


- name: Create build directory
  file:
    path: "{{source_dir}}"
    state: directory

- name: Clone OpenWRT
  git:
    repo: "{{repo}}"
    dest: "{{source_dir}}"
    update: yes
    version: "{{version}}"
  register: source_version

- name: Grab rust targets for hardware profile
  shell: "{{ansible_env.HOME}}/.cargo/bin/rustup target add {{item}}"
  with_items: "{{rust_targets}}"
  ignore_errors: true

#- name: Update Rust
  # shell: "{{ansible_env.HOME}}/.cargo/bin/rustup default nightly; {{ansible_env.HOME}}/.cargo/bin/rustup update"
