gateway: true
source_dir: build
disable_password_login: false
insert_keys: false
dual_radio_mesh: false
keys_to_insert:
  - ""
dropbear_wan_accessible: false
ssh_port: 22
password_auth: 0
default_price: 100
wireless_conf_path: "{{role_path}}/templates/{{conf_to_build}}-wireless.j2"

mesh_subnets:
  - 'fd96::/10'
  - 'fe80::/10'
  - 'ff01::/10'

exit_internal_ip: "fd96::1337:e1f"

private_wifi_key: "ChangeMe"